name: wshop
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - PyYAML
    - python-dotenv # having trouble installing in requirements.txt
    - pandas
    - requests
    - streamlit
    - types-requests
    - types-PyYAML
    # Dev Reqs
    - behave
    - ipdb
    - pytest
    - mypy

